apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: devspaces
  annotations:
    che.eclipse.org/checluster-defaults-cleanup: '{"spec.components.pluginRegistry.openVSXURL":"true"}'
spec:
  devEnvironments:
    defaultNamespace:
      autoProvision: true
      template: devspaces-<username>
    storage:
      pvcStrategy: per-user
    secondsOfInactivityBeforeIdling: -1
    defaultEditor: che-incubator/che-code/latest
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    disableContainerBuildCapabilities: true
    startTimeoutSeconds: 600
  components:
    cheServer:
      debug: false
      logLevel: INFO
    metrics:
      enable: true
    pluginRegistry:
      openVSXURL: 'https://open-vsx.org'
    imagePuller:
      enable: true
      spec:
        images: quarkus-stack-3-27=quay.io/ibm/quarkus-workshop-devspace:ibm-3.27.1;che-code-injector=registry.redhat.io/devspaces/code-rhel9@sha256:5e44792781e3a1da49782a7992ca9979b00d4591129a7d48aa95192d3eb251ae;project-clone=registry.redhat.io/devworkspace/devworkspace-project-clone-rhel9@sha256:3f0619571d6fa2259796f837ebfd0eb0fa225054ac38ed0d144245cccce51515
  gitServices: {}
  networking: {}
