---

- name: Create operator subscription for Devspaces
  kubernetes.core.k8s:
    merge_type:
    - merge
    definition: "{{ lookup('file', 'devspaces_subscription.yaml' ) }}"
  retries: 10
  delay: 30

- name: Create CheCluster for Dev Spaces Namespace
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'che-cluster-ns.yml') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: git_che_result
  until: git_che_result is not failed

- name: Create CheCluster for Dev Spaces
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'che-cluster.yml') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: git_che_result
  until: git_che_result is not failed
